import FaqPage from '@/components/FaqPage'
import PayPalFeesCalculator from '@/components/PayPalFees'
import Payment from '@/components/payment'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Fees Calculator for Customer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PayPalFeesCalculator/>
        <Payment/>
        <FaqPage/>
      </main>
      
    </>
  )
}
